<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Charles" name="ranzhi.Permission" tests="6" failures="0" timestamp="19 十二月 2017 08:02:15 GMT" time="0.000" errors="1">
  <testcase name="editgroup" time="0.000" classname="ranzhi.Permission">
    <skipped/>
  </testcase> <!-- editgroup -->
  <testcase name="addgroup" time="0.000" classname="ranzhi.Permission">
    <skipped/>
  </testcase> <!-- addgroup -->
  <testcase name="shouquan" time="0.000" classname="ranzhi.Permission">
    <skipped/>
  </testcase> <!-- shouquan -->
  <testcase name="groupmembers" time="0.000" classname="ranzhi.Permission">
    <skipped/>
  </testcase> <!-- groupmembers -->
  <testcase name="GetInBackStage" time="0.000" classname="ranzhi.Permission">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at ranzhi.Permission.GetInBackStage(Permission.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- GetInBackStage -->
  <testcase name="groupSQ" time="0.000" classname="ranzhi.Permission">
    <skipped/>
  </testcase> <!-- groupSQ -->
</testsuite> <!-- ranzhi.Permission -->
